<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_propinsi".
 *
 * @property integer $id
 * @property string $nama
 * @property string $p_bsni
 *
 * @property \app\models\WilayahKabupaten[] $wilayahKabupatens
 * @property string $aliasModel
 */
abstract class WilayahPropinsi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_propinsi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'string', 'max' => 100],
            [['p_bsni'], 'string', 'max' => 5]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'p_bsni' => 'P Bsni',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKabupatens()
    {
        return $this->hasMany(\app\models\WilayahKabupaten::className(), ['wilayah_propinsi_id' => 'id']);
    }




}
