<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_kecamatan".
 *
 * @property integer $id
 * @property integer $wilayah_kabupaten_id
 * @property string $nama
 *
 * @property \app\models\WilayahDesa[] $wilayahDesas
 * @property \app\models\WilayahKabupaten $wilayahKabupaten
 * @property string $aliasModel
 */
abstract class WilayahKecamatan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_kecamatan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['wilayah_kabupaten_id'], 'required'],
            [['wilayah_kabupaten_id'], 'integer'],
            [['nama'], 'string', 'max' => 100],
            [['wilayah_kabupaten_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKabupaten::className(), 'targetAttribute' => ['wilayah_kabupaten_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'wilayah_kabupaten_id' => 'Wilayah Kabupaten ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahDesas()
    {
        return $this->hasMany(\app\models\WilayahDesa::className(), ['wilayah_kecamatan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKabupaten()
    {
        return $this->hasOne(\app\models\WilayahKabupaten::className(), ['id' => 'wilayah_kabupaten_id']);
    }




}
